### ISSUE TITLE
cut ties with original repo

### ISSUE THREAD

**Issue by MalikaIhle** [lmu-osc/Introduction-RStudio-Git-GitHub#16]

**Comment by MalikaIhle** [comment]
this can be done as the original repo (zebodo repo) is now linked in the 'about' section.

**Comment by NeuroShepherd** [comment]
FYI for me later on this: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/detaching-a-fork

**Comment by NeuroShepherd** [comment]
Ticket opened https://support.github.com/ticket/personal/0/2820379

**Comment by NeuroShepherd** [comment]
Ticket approved; fork from original broken. Child forks preserved.
