### ISSUE TITLE
tried to add edit and report issue buttons

### ISSUE THREAD

**Issue by MalikaIhle** [lmu-osc/Introduction-RStudio-Git-GitHub#25]
I added   
repo-url: https://github.com/lmu-osc/Introduction-RStudio-Git-GitHub
repo-actions: [edit, issue]
in the yml file and it rendered as expected but it doesn't appear on the published website. 
can you fix and let me know what I did wrong?

**Comment by MalikaIhle** [comment]
now fixed on its own

**Comment by NeuroShepherd** [comment]
@malikaihle probably just a delay in the website redeploying. I recommend waiting 5-10 mins, and force refreshing a few times as the old site versions are generally cached by your browser
